name: 'Copy action'
description: 'Copy files from source path to defined directory'
author: 'APS'

# # Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

# Define your inputs here.
inputs:
  src_path:
    description: 'Source path for copy'
    required: true
    default: '*'
  dst_dir:
    description: 'Destination directory '
    required: true
    default: ''

runs:
  using: node20
  main: dist/index.js
